repos:
  -   repo: https://github.com/wojtek239/cezars-code.git
      rev: v21.10b0
      hooks:
        -   id: black
            args: ['--line-length', '88']
  -   repo: https://github.com/wojtek239/cezars-code.git
      rev: v3.9.2
      hooks:
      -   id: flake8
          args: ['--max-line-length', '88']
  -   repo: https://github.com/wojtek239/cezars-code.git
      rev: v5.9.3
      hooks:
      -   id: isort
          args: ['--line-length', '88']
# REPO CORRECT
# skad sciagam repo