repos:
  -   repo: https://github.com/pre-commit/mirrors-black
      rev: v21.10b0
      hooks:
        -   id: black
            args: ['--line-length', '88']
  -   repo: https://github.com/pre-commit/mirrors-flake8
      rev: v3.9.2
      hooks:
      -   id: flake8
          args: ['--max-line-length', '88']
  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.9.3
      hooks:
      -   id: isort
          args: ['--line-length', '88']
